apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  labels:
    app: weatherapp
spec:
  replicas: 2
  selector:
   matchLabels:
    app: weatherapp
  template:
   metadata:
    labels:
     app: weatherapp
   spec:
    containers:
    - name: redisdb
      image: redis
      ports:
        - containerPort: 6379
    - name: frontend
      image: santhoshkumarhere/weatherapp:2.0
      ports:
        - containerPort: 9001